version: "3.3"
volumes:
  user-db-data:
  friend-db-data:
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "32181:32181/tcp"
    deploy:
      replicas: 1
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    ports:
      - "29092:29092/tcp"
    deploy:
      replicas: 1
  user-db:
    image: oscarfonts/h2:latest
    ports:
      - "21521:1521"
      - "21081:81"
    volumes:
      - "user-db-data:/opt/h2-data"
    deploy:
      replicas: 1
  friends-db:
    image: oscarfonts/h2:latest
    ports:
      - "22521:1521"
      - "22081:81"
    volumes:
      - "friend-db-data:/opt/h2-data"
    deploy:
      replicas: 1
  neo4j:
    image: neo4j:3.5.0
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
    deploy:
      replicas: 1