server:
  port: 8020

management:
  server:
    port: 8021
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

spring:
  application:
    name: User-Service
  data:
    neo4j:
      uri: "bolt://localhost:7687"
      username: neo4j
      password: secret
  cloud:
    stream:
      bindings:
        user:
          binder: kafka
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            concurrency: 1
        friend:
          binder: kafka
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            concurrency: 1

logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG